### PR TITLE
Fix for issue #2 and "allowedPath" check

### PR DESCRIPTION
**Pull request by BlaM**
This is a bugfix for issue #2 and a simple allowedPath check.

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by davglass** [comment]
Wow, @yahoocla seemed to have lost it for a minute..

The PR build for this failed because the coverage dropped. Can you add tests for your new functionality to ensure things work as planned?

**Comment by BlaM** [comment]
I'm leaving for today and will be on vacation now. Will have to get back to that in two weeks or so. Don't know much about mocha, though - so I can't promise anything.

**Comment by davglass** [comment]
Ok, I'll pull it locally this afternoon and add the tests for you :)

**Comment by davglass** [comment]
I added tests and tweaked your logic just a bit here: 80ad1ab101ab764768501ce698c9d9f8f254ecc9

I moved the `allowUpload` check from the beginning `if` to the `if` around the `options.upload` so that the rest of the form is submitted to that URL, it just doesn't allow the file upload.

This landed in `express-busboy@3.0.0`. I made it a major version change since it added a new major feature.

**Comment by BlaM** [comment]
It should not break any existing applications (aka backwards compatible), but: Yayyy 😺

**Pull request merged**
