### PR TITLE
fix overwrite req.body, add mimetype limit

### PR DESCRIPTION
**Pull request by miroslav-grabinskiy**
now can mimetype limit
  bb.extend(app, {
            upload: true,
            path: './public/files',
            allowedPath: /./,
            limits: {
                fileSize: 10 * 1024 * 1024
            },
            mimeTypeLimit: ['image/jpeg', 'image/png']
    });

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by miroslav-grabinskiy** [comment]
proposition for upgrade

**Comment by miroslav-grabinskiy** [comment]
thx, i agree

2016-07-27 22:29 GMT+03:00 Yahoo CLA Bot <notifications@github.com>:

**Comment by davglass** [comment]
This looks pretty good, it failed the build because there are no tests for this feature. No worries, I'll pull it locally and add tests as well as clean up the code a bit.. Thanks!

**Comment by davglass** [comment]
Published in `express-busboy@4.0.0`.

I added tests, refactored some of the code & updated the README.

The only change that I made was that it no longer throws an error in the request. It will just skip the file and continue on. This is how the allowed path error is handled as well. It just doesn't add the files to `req.files`. This is to handle the case of someone uploading several files, say a folder of images, but one happens to be a text file. This way all of the images are still uploaded, only the text file is skipped as it wasn't in the allowed list.

Hopefully that works for you too.

**Comment by miroslav-grabinskiy** [comment]
Thx, good, but one thing I do not like, your module overwriting req.body

An example of my project:

app.use( bodyParser.json() );
app.use( bodyParser.urlencoded({ extended: false }) );
app.use( cookieParser() );

bb.extend(app, {
    upload: true,
    path: './public/files',
    allowedPath: /./,
    limits: {
        fileSize: 10 * 1024 * 1024
    },
    mimeTypeLimit: ['image/jpeg', 'image/png']
});

app.put('/route/json', auth, function(req, res, next) {
        res.status(200).send(req.body) //{}
                                                     //in all requests
                                                     //your module
overwrite req.body ((
                                                     //You can fix this, if
you change your code from
                                                     // req.body = {}
                                                     // to
                                                     // if (!req.body)
req.body = {}
});

app.post('/route/files', function(req, res, next) {
      //logic to work with file
});

**Comment by davglass** [comment]
It is fixed in the version that I published:
https://github.com/yahoo/express-busboy/blob/master/index.js#L35

```js
req.body = req.body || {};
```

**Comment by miroslav-grabinskiy** [comment]
oh, yes ,I have not seen, big thx!

2016-07-28 16:38 GMT+03:00 Dav Glass <notifications@github.com>:

**Pull request merged**
