### PR TITLE
Bump qs version

### PR DESCRIPTION
**Pull request by roderickhsiao**
@davglass @lingyan

change log https://github.com/hapijs/qs/blob/master/CHANGELOG.md 

in the effort of update out-dated dependencies

### CODE REVIEW

**Comment by lingyan** [comment]
:+1:

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by davglass** [comment]
Pushed in `express-busboy@2.4.5`

**Comment by lingyan** [comment]
thanks @davglass

**Comment by roderickhsiao** [comment]
Thanks Dav for prompt response!

**Pull request merged**
